# Generated by Django 3.1.7 on 2021-03-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_garden_plants'),
    ]

    operations = [
        migrations.DeleteModel(
            name='garden',
        ),
        migrations.DeleteModel(
            name='plants',
        ),
    ]
