# Generated by Django 3.1.7 on 2021-04-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover',
            new_name='image',
        ),
    ]
