# Generated by Django 3.1.7 on 2021-04-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210408_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
