# Generated by Django 3.1.7 on 2021-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='imagefile', max_length=500)),
                ('imagefile', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
