# Generated by Django 3.1.7 on 2021-04-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
