# Generated by Django 3.1.7 on 2021-04-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210408_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='Pimg',
            field=models.ImageField(default=False, upload_to='images/'),
        ),
    ]
