# Generated by Django 3.1.7 on 2021-04-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_garden_pimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='Pimg',
        ),
    ]
